// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmb8zoghKO-f3aUGhDbKDMdgr5Te3BBPQ',
    appId: '1:576033526354:web:44c11c7b67ed577e72c58b',
    messagingSenderId: '576033526354',
    projectId: 'efood-f9ef5',
    authDomain: 'efood-f9ef5.firebaseapp.com',
    databaseURL: 'https://efood-f9ef5-default-rtdb.firebaseio.com',
    storageBucket: 'efood-f9ef5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBucqFsYETDTwcRMT0USzzmPGrdN-Ls_Fo',
    appId: '1:576033526354:android:b8e006609805980e72c58b',
    messagingSenderId: '576033526354',
    projectId: 'efood-f9ef5',
    databaseURL: 'https://efood-f9ef5-default-rtdb.firebaseio.com',
    storageBucket: 'efood-f9ef5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8QhYQdT4TlK8Yaj_RtR14T9NxYMvf2i8',
    appId: '1:576033526354:ios:1c41d5b3c5cf1ff672c58b',
    messagingSenderId: '576033526354',
    projectId: 'efood-f9ef5',
    databaseURL: 'https://efood-f9ef5-default-rtdb.firebaseio.com',
    storageBucket: 'efood-f9ef5.appspot.com',
    iosClientId: '576033526354-ecbh4nln0e5fovltra9v63m678g1h869.apps.googleusercontent.com',
    iosBundleId: 'com.example.efood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8QhYQdT4TlK8Yaj_RtR14T9NxYMvf2i8',
    appId: '1:576033526354:ios:1c41d5b3c5cf1ff672c58b',
    messagingSenderId: '576033526354',
    projectId: 'efood-f9ef5',
    databaseURL: 'https://efood-f9ef5-default-rtdb.firebaseio.com',
    storageBucket: 'efood-f9ef5.appspot.com',
    iosClientId: '576033526354-ecbh4nln0e5fovltra9v63m678g1h869.apps.googleusercontent.com',
    iosBundleId: 'com.example.efood',
  );
}
